name: Upload Screenshots to Alpaka

inputs:
  BUILD_ID_ARTIFACT:
    type: string
    required: true
  SCREENSHOTS_DIR:
    type: string
    required: true
  ALPAKA_UPLOAD_KEY:
    required: true
runs:
  using: "composite"
  steps:
    - name: load build_id
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.BUILD_ID_ARTIFACT }}

    - name: Display build_id
      shell: bash
      run: cat build_id.txt

    - name: Upload screenshots
      id: uploadScreenshots
      shell: bash
      env:
        ALPAKA_UPLOAD_URL: https://alpaka.ubique.ch/v1/screenshots/upload
        UPLOAD_KEY: ${{ inputs.ALPAKA_UPLOAD_KEY }}
        SCREENSHOTS_DIR: ${{ inputs.SCREENSHOTS_DIR }}
      run: |
        find "$SCREENSHOTS_DIR" -mindepth 2 -type f -exec cp {} "$SCREENSHOTS_DIR"/ \;
        BUILD_ID=$(cat build_id.txt)
        BATCH_SIZE=8
        
        # Collect screenshots into an array
        mapfile -t screenshots < <(find "$SCREENSHOTS_DIR" -maxdepth 1 -type f)
        
        total=${#screenshots[@]}
        echo "Found $total screenshots"
        
        batch_start=0
        batch_num=1
        while [ $batch_start -lt $total ]; do
          echo "Uploading batch $batch_num..."
          curl_cmd="curl -X POST $ALPAKA_UPLOAD_URL"
          for ((i=batch_start; i<batch_start+BATCH_SIZE && i<total; i++)); do
            curl_cmd="$curl_cmd -F screenshots=@${screenshots[$i]}"
          done
        
          curl_cmd="$curl_cmd -F 'data={\"uploadKey\":\"$UPLOAD_KEY\",\"buildId\":\"$BUILD_ID\"};type=application/json'"
          echo "Running: $curl_cmd"
          response=$(eval $curl_cmd)
          echo "Response: $response"
        
          if ! echo "$response" | grep -q '"success"'; then
            echo "Screenshot upload failed (no success flag)!"
            exit 1
          fi
        
          if echo "$response" | grep -q '"failure"'; then
            echo "Screenshot upload failed (failure found)!"
            exit 1
          fi
        
          batch_start=$((batch_start + BATCH_SIZE))
          batch_num=$((batch_num + 1))
        done
