name: Upload Screenshots to Alpaka

inputs:
  BUILD_ID_ARTIFACT:
    type: string
    required: true
  SCREENSHOTS_DIR:
    type: string
    required: true
  ALPAKA_UPLOAD_KEY:
    required: true
runs:
  using: "composite"
  steps:
    - name: load build_id
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.BUILD_ID_ARTIFACT }}

    - name: Display build_id
      shell: bash
      run: cat build_id.txt

    - name: Upload screenshots
      id: uploadScreenshots
      shell: bash
      env:
        ALPAKA_UPLOAD_URL: https://alpaka.ubique.ch/v1/screenshots/upload
        UPLOAD_KEY: ${{ inputs.ALPAKA_UPLOAD_KEY }}
        SCREENSHOTS_DIR: ${{ inputs.SCREENSHOTS_DIR }}
      run: |
        curl_args=( -X POST "$ALPAKA_UPLOAD_URL" )
        while IFS= read -r -d '' file; do
          curl_args+=( -F "screenshots=@$file" )
        done < <(find "$SCREENSHOTS_DIR" -type f -print0)

        BUILD_ID=$(cat build_id.txt)
        curl_args+=( -F "data={\"uploadKey\":\"$UPLOAD_KEY\",\"buildId\":\"$BUILD_ID\"};type=application/json" )
        echo "Running: curl ${curl_args[*]}"
        response=$(curl "${curl_args[@]}")
        echo "Response: $response"
        
        if ! echo "$response" | grep -q '"success"'; then
          echo "Screenshot upload failed (no success flag)!"
          exit 1
        fi
        
        if echo "$response" | grep -q '"failure"'; then
          echo "Screenshot upload failed (failure found)!"
          exit 1
        fi
