name: SSH Setup
description: >
  Ensures ~/.ssh is a valid directory, loads the given private key via ssh-agent,
  and adds the GitHub host key fingerprints to known_hosts.

inputs:
  ssh-private-key:
    description: 'The SSH private key to load into the ssh-agent.'
    required: true

runs:
  using: composite
  steps:
    - name: Ensure ~/.ssh is a directory
      shell: bash
      run: |
        if [ -e "$HOME/.ssh" ] && [ ! -d "$HOME/.ssh" ]; then
          echo "~/.ssh exists but is not a directory. Deleting it..."
          rm -f "$HOME/.ssh"
          echo "Removed ~/.ssh."
        else
          echo "~/.ssh is either a directory or does not exist. No action needed."
        fi

    - name: Add SSH Key
      uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - name: Add GitHub SSH keys to the known_hosts file
      shell: bash
      run: |
        cat >> ~/.ssh/known_hosts <<EOF
        github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
        github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
        github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
        EOF
