name: 'BuildAndUpload'
description: 'Build an Android app and upload it to UBDiag'
inputs:
  buildNumber:
    description: 'A unique build number'
    required: true
  projectKey:
    description: 'The project key for this build'
    required: true
  flavor:
    description: 'The Android app flavor'
    required: true
  buildType:
    description: 'The Android build type (debug, release, etc.)'
    required: false
    default: 'release'
  app:
    description: 'The app identifier for this build'
    required: true
  appModuleDirectory:
    description: 'The project folder of the app module'
    required: true
  buildTask:
    description: 'An optional custom gradle build task'
    required: false
    default: ''
  runTestTask:
    description: 'Whether or not the test gradle task should be run'
    required: false
    default: 'false'
  runCrashlyticsNativeSymbolsUploadTask:
    description: 'Whether or not the crashlytics native symbols upload task should be run'
    required: false
    default: 'false'
  gradleProps:
    description: 'Custom properties to be passed to the gradle command'
    required: false
    default: ''
  uploadTarget:
    description: 'The upload target, can be either "ubdiag", "playstore" or an empty string if no upload should be done'
    required: false
    default: ''
  backendEndpoint:
    description: 'The backend endpoint for the UBDiag upload'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://ubinnovation/android-build-environment:latest'
  entrypoint: '/main.sh'
  args:
    - ${{ inputs.buildNumber }}
    - ${{ inputs.projectKey }}
    - ${{ inputs.flavor }}
    - ${{ inputs.buildType }}
    - ${{ inputs.app }}
    - ${{ inputs.appModuleDirectory }}
    - ${{ inputs.buildTask }}
    - ${{ inputs.runTestTask }}
    - ${{ inputs.runCrashlyticsNativeSymbolsUploadTask }}
    - ${{ inputs.gradleProps }}
    - ${{ inputs.uploadTarget }}
    - ${{ inputs.backendEndpoint }}
