name: 'BuildAndUpload'
description: 'Build an Android app and upload it to UBDiag'
inputs:
  projectKey:
    description: ''
    required: true
  configuration:
    description: ''
    required: true
  app:
    description: ''
    required: true
  doUpload:
    description: 'actually upload app to UBDiag'
    required: false
  buildCommand:
    description: 'optional custom buildCommand'
    required: false
  appModuleDirectory:
    description: 'specify project folder of app module'
    required: true
  gradleProps:
    description: 'custom properties to be passed to gradle cmd'
    required: false
  buildNumber:
    description: 'unique build number'
    required: true
  backendEndpoint:
    description: 'backend endpoint for upload'
    required: true
runs:
  using: 'docker'
  image: 'docker://ubinnovation/android-build-environment:1.0.1'
  entrypoint: '/main.sh'
  args:
    - ${{ inputs.projectKey }}
    - ${{ inputs.configuration }}
    - ${{ inputs.app }}
    - ${{ inputs.doUpload }}
    - ${{ inputs.buildCommand }}
    - ${{ inputs.appModuleDirectory }}
    - ${{ inputs.gradleProps }}
    - ${{ inputs.buildNumber }}
    - ${{ inputs.backendEndpoint }}
