name: Run a gradle task

on:
  workflow_call:
    inputs:
      task:
        type: string
        required: true
      gradle-args:
        type: string
        required: false
      concurrency-group:
        type: string
        required: false
        default: ${{ github.workflow }}-${{ github.ref }}
      working-directory:
        type: string
        default: './'
        required: false
        description: 'The working directory of the script, for projects where the gradle project is not in the root folder. Must end with a slash.'
      runs-on:
        type: string
        required: false
        default: '["k8s-runner"]'
      android-image-version:
        type: string
        required: false
        default: '2026.03.1-ndk'
        description: The Android image version to use. Default is 2026.03.1-ndk.
      use-git-lfs:
        required: false
        default: false
        type: boolean
        description: 'Use git lfs during repository checkout'
    secrets:
      UB_ARTIFACTORY_URL:
        required: true
      UB_ARTIFACTORY_REPO_ANDROID:
        required: true
      UB_ARTIFACTORY_USER:
        required: true
      UB_ARTIFACTORY_PASSWORD:
        required: true

jobs:
  task:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    container:
      image: cimg/android:${{ inputs.android-image-version }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    timeout-minutes: 60
    concurrency:
      # Cancel any previous runs that have not yet finished for the configured concurrency group
      group: ${{ inputs.concurrency-group }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          lfs: ${{ inputs.use-git-lfs }}
      - name: Install zstd
        run: sudo apt-get install -y zstd

      - name: Run Gradle task
        run: ./gradlew ${{ inputs.task }} ${{ inputs.gradle-args }}
        env:
          UB_ARTIFACTORY_URL: ${{ secrets.UB_ARTIFACTORY_URL }}
          UB_ARTIFACTORY_REPO_ANDROID: ${{ secrets.UB_ARTIFACTORY_REPO_ANDROID }}
          UB_ARTIFACTORY_URL_ANDROID: '${{ secrets.UB_ARTIFACTORY_URL }}${{ secrets.UB_ARTIFACTORY_REPO_ANDROID }}'
          UB_ARTIFACTORY_USER: ${{ secrets.UB_ARTIFACTORY_USER }}
          UB_ARTIFACTORY_PASSWORD: ${{ secrets.UB_ARTIFACTORY_PASSWORD }}
