name: Run Code Quality Checks

on:
  workflow_call:
    inputs:
      flavor:
        type: string
        required: true
      app-module:
        type: string
        required: false
        default: 'app'
        description: 'The gradle app module (e.g. custom "android:androidApp")'
      run-coeus:
        type: boolean
        required: false
        default: false
      skip-rules:
        type: string
        required: false
        default: ''
      run-tests:
        type: boolean
        required: false
        default: false
      run-lint:
        type: boolean
        required: false
        default: true
      run-sonarqube:
        type: boolean
        required: false
        default: false
      runs-on:
        type: string
        required: false
        default: '["k8s-runner"]'
      android-image-version:
        type: string
        required: false
        default: '2026.03.1-ndk'
        description: The Android image version to use. Default is 2026.03.1-ndk.
      setup-rust:
        required: false
        default: false
        type: boolean
      jdk:
        type: string
        required: false
        default: '21'
        description: 'The JDK version to use. Default is 21.'
      use-git-lfs:
        required: false
        default: false
        type: boolean
        description: 'Use git lfs during repository checkout'
      pre-build-script:
        required: false
        type: string
        default: ''
        description: 'Bash script that is executed before the actual build'
    secrets:
      ANDROID_JENKINS_PAT:
        required: true
      UB_ARTIFACTORY_URL_ANDROID:
        required: true
      UB_ARTIFACTORY_USER:
        required: true
      UB_ARTIFACTORY_PASSWORD:
        required: true
      UBIQUE_POEDITOR_API_KEY:
        required: true
      UBIQUE_SONAR_TOKEN:
        required: false
      ACR_REGISTRY:
        required: false
        description: Required if run-coeus is true
      ACR_USERNAME:
        required: false
        description: Required if run-coeus is true
      ACR_PASSWORD:
        required: false
        description: Required if run-coeus is true
      ADDITIONAL_GRADLE_PROPS:
        required: false
      SENTRY_AUTH_TOKEN:
        required: false

jobs:
  code_quality:
    name: Run code quality checks
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    env:
      GRADLE_OPTS: "-Dorg.gradle.workers.max=8"
      CMAKE_BUILD_PARALLEL_LEVEL: 8
      "ORG_GRADLE_PROJECT_kotlin.compiler.execution.strategy": "in-process"
    container:
      image: cimg/android:${{ inputs.android-image-version }}
    timeout-minutes: 60
    concurrency:
      # Cancel any previous runs that have not yet finished for this workflow and git ref
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Setup Android app build environment
        id: setup
        uses: UbiqueInnovation/actions-android/.github/actions/android-app-setup@v2
        with:
          checkout-token: ${{ secrets.ANDROID_JENKINS_PAT }}
          use-git-lfs: ${{ inputs.use-git-lfs }}
          jdk: ${{ inputs.jdk }}
          setup-rust: ${{ inputs.setup-rust }}
          flavor: ${{ inputs.flavor }}
          app-module: ${{ inputs.app-module }}
          gradle-cache-job-id: '${{ inputs.jdk }}-${{ inputs.app-module }}'
          pre-build-script: ${{ inputs.pre-build-script }}

      # Set Gradle properties for reuse in multiple steps
      - name: Set Gradle Properties
        id: gradle
        shell: bash
        run: |
          gradleProps="-PsentryAuthToken=${{ secrets.SENTRY_AUTH_TOKEN }} -PubiqueMavenUrl=${{ secrets.UB_ARTIFACTORY_URL_ANDROID }} -PubiqueMavenUser=${{ secrets.UB_ARTIFACTORY_USER }} -PubiqueMavenPass=${{ secrets.UB_ARTIFACTORY_PASSWORD }} -PubiquePoEditorAPIKey=${{ secrets.UBIQUE_POEDITOR_API_KEY }} ${{ secrets.ADDITIONAL_GRADLE_PROPS }}"
          echo "gradle-properties=$gradleProps" >> "$GITHUB_OUTPUT"

      # Run Unit Tests
      - name: Run Unit Tests
        id: tests
        if: ${{ fromJSON(inputs.run-tests) }}
        run: ./gradlew :${{ inputs.app-module }}:test${{ steps.setup.outputs.flavor-capitalized }}DebugUnitTest ${{ steps.gradle.outputs.gradle-properties }} ${{ github.run_attempt > 1 && '--stacktrace --info' || '' }} --daemon

      # Run Android Lint checks
      - name: Run Lint
        id: lint
        if: ${{ fromJSON(inputs.run-lint) }}
        run: ./gradlew :${{ inputs.app-module }}:lint${{ steps.setup.outputs.flavor-capitalized }}Debug ${{ steps.gradle.outputs.gradle-properties }} ${{ github.run_attempt > 1 && '--stacktrace --info' || '' }} --daemon

      # Run Sonarqube code analysis
      - name: Run Sonarqube
        id: sonarqube
        if: ${{ fromJSON(inputs.run-sonarqube) }}
        env:
          GITHUB_TOKEN: ${{ secrets.ANDROID_JENKINS_PAT }}
          SONAR_TOKEN: ${{ secrets.UBIQUE_SONAR_TOKEN }}
        run: ./gradlew :${{ inputs.app-module }}:sonar ${{ steps.gradle.outputs.gradle-properties }} ${{ github.run_attempt > 1 && '--stacktrace --info' || '' }} --daemon

      # Publish test results to pull requests
      - name: Publish Unit Test Results
        if: ${{ fromJSON(inputs.run-tests) && steps.tests.outcome == 'success' }}
        uses: EnricoMi/publish-unit-test-result-action@v2.21.0
        with:
          check_name: 'Unit Test Results'
          files: ${{ steps.setup.outputs.app-module-path }}/build/test-results/**/*.xml

  coeus:
    if: ${{ github.event_name == 'pull_request' && fromJSON(inputs.run-coeus) }}
    name: Run coeus binary analysis
    runs-on: ['docker']
    container:
      image: cimg/android:${{ inputs.android-image-version }}
      options: '--group-add=123'
    timeout-minutes: 60
    concurrency:
      # Cancel any previous runs that have not yet finished for this workflow and git ref
      group: ${{ github.workflow }}-${{ github.ref }}-coeus
      cancel-in-progress: true
    steps:
      - name: Setup Android app build environment
        id: setup
        uses: UbiqueInnovation/actions-android/.github/actions/android-app-setup@v2
        with:
          checkout-token: ${{ secrets.ANDROID_JENKINS_PAT }}
          use-git-lfs: ${{ inputs.use-git-lfs }}
          jdk: ${{ inputs.jdk }}
          setup-rust: ${{ inputs.setup-rust }}
          flavor: ${{ inputs.flavor }}
          app-module: ${{ inputs.app-module }}
          gradle-cache-job-id: '${{ inputs.jdk }}-${{ inputs.app-module }}'
          pre-build-script: ${{ inputs.pre-build-script }}

      # Set Gradle properties for reuse in multiple steps
      - name: Set Gradle Properties
        id: gradle
        shell: bash
        run: |
          gradleProps="-PsentryAuthToken=${{ secrets.SENTRY_AUTH_TOKEN }} -PubiqueMavenUrl=${{ secrets.UB_ARTIFACTORY_URL_ANDROID }} -PubiqueMavenUser=${{ secrets.UB_ARTIFACTORY_USER }} -PubiqueMavenPass=${{ secrets.UB_ARTIFACTORY_PASSWORD }} -PubiquePoEditorAPIKey=${{ secrets.UBIQUE_POEDITOR_API_KEY }} ${{ secrets.ADDITIONAL_GRADLE_PROPS }}"
          echo "gradle-properties=$gradleProps" >> "$GITHUB_OUTPUT"

      # Run Coeus
      - name: Assemble the APK for static code analysis
        id: coeus-assemble
        run: ./gradlew :${{ inputs.app-module }}:assemble${{ steps.setup.outputs.flavor-capitalized }}Release ${{ steps.gradle.outputs.gradle-properties }} ${{ github.run_attempt > 1 && '--stacktrace --info' || '' }} --daemon

      - name: Find APK and Mapping
        id: find-apk
        shell: bash
        run: |
          export apk=`find $GITHUB_WORKSPACE/${{ steps.setup.outputs.app-module-path }}/build/outputs/apk/ -name '*.apk'`
          export mapping=`find $GITHUB_WORKSPACE/${{ steps.setup.outputs.app-module-path }}/build/outputs/mapping/ -name 'mapping.txt' || true`
          echo "apk=${apk//__w/home\/runner\/_work\/}" >> $GITHUB_OUTPUT
          echo "mapping=${mapping//__w/home\/runner\/_work\/}" >> $GITHUB_OUTPUT

      - name: Docker login for Azure registry
        id: coeus-docker-login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Run Coeus
        id: coeus
        # See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
        # and https://github.community/t/set-output-truncates-multiline-strings/16852/
        # Don't fail CI here, print comment first.
        run: |
          OUTPUT=`docker run -i -e SKIP_RULES="${{ inputs.skip-rules }}" -v ${{ steps.find-apk.outputs.mapping }}:/home/coeus/mapping.txt -v ${{ steps.find-apk.outputs.apk }}:/home/coeus/check-apk.apk ubique.azurecr.io/coeus-docker || true`
          echo "$OUTPUT" >> $GITHUB_STEP_SUMMARY
          echo "COEUS_OUTPUT<<EOF" >> $GITHUB_ENV
          echo "$OUTPUT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # Find and create/replace the comment the Coeus Analysis output
      - name: Find Coeus Comment
        id: coeus-comment-find
        uses: peter-evans/find-comment@1769778a0c5bd330272d749d12c036d65e70d39d
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Coeus Binary Analysis Results'

      - name: Comment Coeus Output
        id: coeus-comment
        uses: peter-evans/create-or-update-comment@b95e16d2859ad843a14218d1028da5b2c4cbc4b4
        with:
          comment-id: ${{ steps.coeus-comment-find.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ env.COEUS_OUTPUT }}
          edit-mode: replace

      # Fail the CI if Coeus found at least one error, i.e. if grepping for an error returns a result
      - name: Fail CI if Coeus has errors
        id: coeus-check-fail
        run: |
          echo '${{ env.COEUS_OUTPUT }}' | (! grep '\[ERROR\]')
