name: Run Code Quality Checks

on:
  workflow_call:
    inputs:
      flavor:
        type: string
        required: true
      appModule:
        type: string
        required: false
        default: "app"
      runCoeus:
        type: boolean
        required: false
        default: false
      skipRules:
        type: string
        required: false
        default: ""
      runTests:
        type: boolean
        required: false
        default: false
      runLint:
        type: boolean
        required: false
        default: true
      runSonarqube:
        type: boolean
        required: false
        default: false
      self_hosted_cache_endpoint:
        required: false
        default: "truenas.local.lan"
        type: string
        description: Should be set for selfhosted builds, but build won't fail without it
      self_hosted_cache_port:
        required: false
        default: 9000
        type: number
      self_hosted_cache_bucket:
        required: false
        default: github-actions-cache
        type: string
      self_hosted_cache_region:
        required: false
        default: local
        type: string

    secrets:
      ANDROID_JENKINS_PAT:
        required: true
      UB_ARTIFACTORY_URL_ANDROID:
        required: true
      UB_ARTIFACTORY_USERNAME:
        required: true
      UB_ARTIFACTORY_PASSWORD:
        required: true
      UBIQUE_POEDITOR_API_KEY:
        required: true
      UBIQUE_SONAR_TOKEN:
        required: true
      ACR_REGISTRY:
        required: false
        description: Required if runCoeus is true
      ACR_USERNAME:
        required: false
        description: Required if runCoeus is true
      ACR_PASSWORD:
        required: false
        description: Required if runCoeus is true
      ADDITIONAL_GRADLE_PROPS:
        required: false
      SENTRY_AUTH_TOKEN:
        required: false
      self_hosted_cache_access_key:
        required: false
        description: Must be set to use selfhosted cache
      self_hosted_cache_secret_key:
        required: false

jobs:
  code_quality:
    name: Run code quality checks
    runs-on: ["k8s-runner"]
    container:
      image: cimg/android:2024.04.1
    timeout-minutes: 60
    concurrency:
      # Cancel any previous runs that have not yet finished for this workflow and git ref
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      # Checkout repository and submodules
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.ANDROID_JENKINS_PAT }}
          submodules: "recursive"
          lfs: "true"

      # Set build variables for reuse in multiple steps
      - name: Set Build Variables
        id: vars
        shell: bash
        run: |
          export flavor=${{ inputs.flavor }}
          echo "flavor_capitalized=${flavor~}" >> "$GITHUB_OUTPUT"
          export gradleProps="-PsentryAuthToken=${{ secrets.SENTRY_AUTH_TOKEN }} -PubiqueMavenUrl=${{ secrets.UB_ARTIFACTORY_URL_ANDROID }} -PubiqueMavenUser=${{ secrets.UB_ARTIFACTORY_USERNAME }} -PubiqueMavenPass=${{ secrets.UB_ARTIFACTORY_PASSWORD }} -PubiquePoEditorAPIKey=${{ secrets.UBIQUE_POEDITOR_API_KEY }} ${{ secrets.ADDITIONAL_GRADLE_PROPS }}"
          echo "gradle_properties=$gradleProps" >> "$GITHUB_OUTPUT"

      # Setup JDK environment
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache SonarCloud packages on selfhosted MinIO
        if: ${{ fromJSON(inputs.runSonarqube) }}
        uses: tespkg/actions-cache@v1.7.1
        with:
          endpoint: ${{ inputs.self_hosted_cache_endpoint }}
          port: ${{ inputs.self_hosted_cache_port }}
          insecure: true
          accessKey: ${{ secrets.self_hosted_cache_access_key }}
          secretKey: ${{ secrets.self_hosted_cache_secret_key }}
          bucket: ${{ inputs.self_hosted_cache_bucket }}
          region: ${{ inputs.self_hosted_cache_region }}
          use-fallback: false
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Run Unit Tests
      - name: Run Unit Tests
        id: tests
        if: ${{ fromJSON(inputs.runTests) }}
        uses: gradle/actions/setup-gradle@v3.1.0
        with:
          arguments: :${{ inputs.appModule }}:test${{ steps.vars.outputs.flavor_capitalized }}DebugUnitTest ${{ steps.vars.outputs.gradle_properties }} --daemon
          cache-disabled: true

      # Run Android Lint checks
      - name: Run Lint
        id: lint
        if: ${{ fromJSON(inputs.runLint) }}
        uses: gradle/actions/setup-gradle@v3.1.0
        with:
          arguments: :${{ inputs.appModule }}:lint${{ steps.vars.outputs.flavor_capitalized }}Debug ${{ steps.vars.outputs.gradle_properties }} --daemon
          cache-disabled: true

      # Run Sonarqube code analysis
      - name: Run Sonarqube
        id: sonarqube
        if: ${{ fromJSON(inputs.runSonarqube) }}
        uses: gradle/actions/setup-gradle@v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.ANDROID_JENKINS_PAT }}
          SONAR_TOKEN: ${{ secrets.UBIQUE_SONAR_TOKEN }}
        with:
          arguments: :${{ inputs.appModule }}:sonarqube ${{ steps.vars.outputs.gradle_properties }} --daemon
          cache-disabled: true

      # Publish test results to pull requests
      - name: Publish Unit Test Results
        if: ${{ fromJSON(inputs.runTests) && steps.tests.outcome == 'success' }}
        uses: EnricoMi/publish-unit-test-result-action@v1.36
        with:
          check_name: "Unit Test Results"
          files: ${{ inputs.appModule }}/build/test-results/**/*.xml
  coeus:
    #if: ${{ github.event_name == 'pull_request' && fromJSON(inputs.runCoeus) }}
    name: Run coeus binary analysis
    runs-on: ["docker"]
    container:
      image: cimg/android:2024.04.1
    timeout-minutes: 60
    concurrency:
      # Cancel any previous runs that have not yet finished for this workflow and git ref
      group: ${{ github.workflow }}-${{ github.ref }}-coeus
      cancel-in-progress: true
    steps:
      # Checkout repository and submodules
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.ANDROID_JENKINS_PAT }}
          submodules: "recursive"
          lfs: "true"

      # Set build variables for reuse in multiple steps
      - name: Set Build Variables
        id: vars
        shell: bash
        run: |
          export flavor=${{ inputs.flavor }}
          echo "flavor_capitalized=${flavor~}" >> "$GITHUB_OUTPUT"
          export gradleProps="-PsentryAuthToken=${{ secrets.SENTRY_AUTH_TOKEN }} -PubiqueMavenUrl=${{ secrets.UB_ARTIFACTORY_URL_ANDROID }} -PubiqueMavenUser=${{ secrets.UB_ARTIFACTORY_USERNAME }} -PubiqueMavenPass=${{ secrets.UB_ARTIFACTORY_PASSWORD }} -PubiquePoEditorAPIKey=${{ secrets.UBIQUE_POEDITOR_API_KEY }} ${{ secrets.ADDITIONAL_GRADLE_PROPS }}"
          echo "gradle_properties=$gradleProps" >> "$GITHUB_OUTPUT"

      # Setup JDK environment
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: "zulu"
          java-version: "17"
      # Run Coeus
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Assemble the APK for static code analysis
        id: coeus-assemble
        uses: gradle/actions/setup-gradle@v3.1.0
        with:
          arguments: :${{ inputs.appModule }}:assemble${{ steps.vars.outputs.flavor_capitalized }}Release ${{ steps.vars.outputs.gradle_properties }} --daemon
          cache-disabled: true
      - name: Find APK and Mapping
        id: find-apk
        run: |
          apk=`find ${{ github.workspace }}/${{ inputs.appModule }}/build/outputs/apk/ -name '*.apk'`
          mapping=`find ${{ github.workspace }}/${{ inputs.appModule }}/build/outputs/mapping/ -name 'mapping.txt' || true`
          echo "apk=$apk" >> $GITHUB_OUTPUT
          echo "mapping=$mapping" >> $GITHUB_OUTPUT
      - name: Docker login for Azure registry
        id: coeus-docker-login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Run Coeus
        id: coeus
        # See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
        # and https://github.community/t/set-output-truncates-multiline-strings/16852/
        # Don't fail CI here, print comment first.
        run: |
          OUTPUT=`docker run -i -e SKIP_RULES="${{ inputs.skipRules }}" -v ${{ steps.find-apk.outputs.mapping }}:/home/coeus/mapping.txt -v ${{ steps.find-apk.outputs.apk }}:/home/coeus/check-apk.apk ubique.azurecr.io/coeus-docker || true`
          echo "$OUTPUT" >> $GITHUB_STEP_SUMMARY
          echo "COEUS_OUTPUT<<EOF" >> $GITHUB_ENV
          echo "$OUTPUT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # Find and create/replace the comment the Coeus Analysis output
      - name: Find Coeus Comment
        id: coeus-comment-find
        uses: peter-evans/find-comment@1769778a0c5bd330272d749d12c036d65e70d39d
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "Coeus Binary Analysis Results"

      - name: Comment Coeus Output
        id: coeus-comment
        uses: peter-evans/create-or-update-comment@b95e16d2859ad843a14218d1028da5b2c4cbc4b4
        with:
          comment-id: ${{ steps.coeus-comment-find.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ env.COEUS_OUTPUT }}
          edit-mode: replace

      # Fail the CI if Coeus found at least one error, i.e. if grepping for an error returns a result
      - name: Fail CI if Coeus has errors
        id: coeus-check-fail
        run: |
          echo '${{ env.COEUS_OUTPUT }}' | (! grep '\[ERROR\]')
