name: Build and publish library artifact

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        default: './'
        required: false
        description: 'The working directory of the script, for projects where the gradle project is not in the root folder. Must end with a slash.'
      lib-module:
        type: string
        required: false
        default: 'lib'
        description: 'The name of the gradle module of the library (similar to the app module)'
      version-name-suffix:
        type: string
        default: ''
        required: false
        description: 'A suffix to be appended to the version name. Empty by default for release builds'
      gradle-properties-path:
        type: string
        default: './gradle.properties'
        required: false
        description: 'The path to the gradle.properties file that contains the POM_ARTIFACT_VERSION'
      jdk:
        type: string
        required: false
        default: '21'
        description: The JDK version to use. Default is 21.
      runs-on:
        type: string
        required: false
        default: '["k8s-runner"]'
      android-image-version:
        type: string
        required: false
        default: '2026.03.1-ndk'
        description: The Android image version to use. Default is 2026.03.1-ndk.
      setup-rust:
        required: false
        default: false
        type: boolean
      use-git-lfs:
        required: false
        default: false
        type: boolean
        description: 'Use git lfs during repository checkout'
      pre-build-script:
        required: false
        type: string
        default: ''
        description: 'Bash script that is executed before the actual build'
    secrets:
      ANDROID_JENKINS_PAT:
        required: true
      UB_ARTIFACTORY_URL_ANDROID:
        required: true
      UB_ARTIFACTORY_USER:
        required: true
      UB_ARTIFACTORY_PASSWORD:
        required: true

jobs:
  build:
    name: Build library
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    env:
      GRADLE_OPTS: "-Dorg.gradle.workers.max=8 -Dorg.gradle.daemon=false"
      "ORG_GRADLE_PROJECT_kotlin.compiler.execution.strategy": "in-process"
    container:
      image: cimg/android:${{ inputs.android-image-version }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    timeout-minutes: 60
    concurrency:
      # Cancel any previous runs that have not yet finished for the configured concurrency group
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Setup Android environment
        uses: UbiqueInnovation/actions-android/.github/actions/android-base-setup@v2
        with:
          checkout-token: ${{ secrets.ANDROID_JENKINS_PAT }}
          use-git-lfs: ${{ inputs.use-git-lfs }}
          jdk: ${{ inputs.jdk }}
          setup-rust: ${{ inputs.setup-rust }}
          gradle-cache-job-id: '${{ inputs.jdk }}-${{ inputs.lib-module }}'
          pre-build-script: ${{ inputs.pre-build-script }}

      # Append version name suffix
      - name: Append version name suffix
        id: version
        if: ${{ inputs.version-name-suffix }} != ''
        run: |
          if grep -q "VERSION_NAME=" ${{ inputs.gradle-properties-path }}; then
            sed -i "/^VERSION_NAME=/s/$/${{ inputs.version-name-suffix }}/" ${{ inputs.gradle-properties-path }}
          else
            echo "Could not find VERSION_NAME gradle property in ${{ inputs.gradle-properties-path }}"
            exit 1
          fi

      # Run the Gradle publish task
      - name: Build and publish artifact
        run: |
          ./gradlew :${{ inputs.lib-module }}:publish \
            ${{ github.run_attempt > 1 && '--stacktrace --info' || '' }} \
            -PubiqueMavenUrl=${{ secrets.UB_ARTIFACTORY_URL_ANDROID }} \
            -PubiqueMavenUser=${{ secrets.UB_ARTIFACTORY_USER }} \
            -PubiqueMavenPass=${{ secrets.UB_ARTIFACTORY_PASSWORD }}
        env:
          UB_ARTIFACTORY_URL_ANDROID: ${{ secrets.UB_ARTIFACTORY_URL_ANDROID }}
          UB_ARTIFACTORY_USER: ${{ secrets.UB_ARTIFACTORY_USER }}
          UB_ARTIFACTORY_PASSWORD: ${{ secrets.UB_ARTIFACTORY_PASSWORD }}
