name: Build and Upload to Play Store

on:
  workflow_call:
    inputs:
      flavor:
        type: string
        required: true
      app-module:
        type: string
        required: false
        default: 'app'
        description: 'The gradle app module (e.g. custom "android:androidApp")'
      setup-rust:
        required: false
        default: false
        type: boolean
      runs-on:
        type: string
        required: false
        default: '["k8s-runner"]'
      jdk:
        type: string
        required: false
        default: '21'
        description: 'The JDK version to use. Default is 21.'
      android-image-version:
        type: string
        required: false
        default: '2026.03.1-ndk'
        description: 'The Android image version to use. Default is 2026.03.1-ndk.'
      sentry-log-level:
        type: string
        required: false
        default: 'warn'
        description: 'The Sentry log level to use. Default is "warn". Other options are "trace", "debug", "info" and "error"'
      working-directory:
        type: string
        default: './'
        required: false
        description: 'The working directory of the script, for projects where the gradle project is not in the root folder. Must end with a slash.'
      use-git-lfs:
        type: boolean
        required: false
        default: false
        description: 'Use git lfs during repository checkout'
    secrets:
      ANDROID_JENKINS_PAT:
        required: true
      UB_ARTIFACTORY_URL_ANDROID:
        required: true
      UB_ARTIFACTORY_USER:
        required: true
      UB_ARTIFACTORY_PASSWORD:
        required: true
      UBIQUE_POEDITOR_API_KEY:
        required: true
      ADDITIONAL_GRADLE_PROPS:
        required: false
      SENTRY_AUTH_TOKEN:
        required: false
      UPLOAD_KEY_STORE_PASSWORD:
        required: true
      UPLOAD_KEY_PASSWORD:
        required: true
      ANDROID_PUBLISHER_CREDENTIALS:
        required: true

jobs:
  build:
    name: Build
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    container:
      image: cimg/android:${{ inputs.android-image-version }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    timeout-minutes: 60
    concurrency:
      # Cancel any previous runs that have not yet finished for this workflow, git ref and app module (for apps that have multiple apps in the same workflow)
      group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.app-module }}
      cancel-in-progress: true
    env:
      AAB_STAGING_DIR: .tmp/publishing_aab
    outputs:
      flavor_capitalized: ${{ steps.setup.outputs.flavor_capitalized }}
      app_module_path: ${{ steps.setup.outputs.app_module_path }}
    steps:
      - name: Setup Android app build environment
        id: setup
        uses: UbiqueInnovation/actions-android/.github/actions/android-app-setup@v2
        with:
          checkout-token: ${{ secrets.ANDROID_JENKINS_PAT }}
          use-git-lfs: ${{ inputs.use-git-lfs }}
          jdk: ${{ inputs.jdk }}
          setup-rust: ${{ inputs.setup-rust }}
          flavor: ${{ inputs.flavor }}
          app-module: ${{ inputs.app-module }}
          gradle-cache-job-id: '${{ inputs.jdk }}-${{ inputs.app-module }}'

      # Build the app
      - name: Build app
        run: |
          ./gradlew :${{ inputs.app-module }}:bundle${{ steps.setup.outputs.flavor_capitalized }}ReleaseUpload \
            ${{ github.run_attempt > 1 && '--stacktrace --info' || '' }} \
            -PubiqueMavenUrl=${{ secrets.UB_ARTIFACTORY_URL_ANDROID }} \
            -PubiqueMavenUser=${{ secrets.UB_ARTIFACTORY_USER }} \
            -PubiqueMavenPass=${{ secrets.UB_ARTIFACTORY_PASSWORD }} \
            -PubiquePoEditorAPIKey=${{ secrets.UBIQUE_POEDITOR_API_KEY }} \
            -Pbuild_id=${{ steps.setup.outputs.build_id }} \
            -Pbuild_number=${{ steps.setup.outputs.build_number }} \
            -Pbuild_batch=release${{ steps.setup.outputs.build_batch }} \
            -Pbranch=${{ github.ref_name }} \
            -PcommitHash=${{ github.sha }} \
            ${{ secrets.ADDITIONAL_GRADLE_PROPS }}
        env:
          UPLOAD_KEY_STORE_PASSWORD: ${{ secrets.UPLOAD_KEY_STORE_PASSWORD }}
          UPLOAD_KEY_PASSWORD: ${{ secrets.UPLOAD_KEY_PASSWORD }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_LOG_LEVEL: ${{ github.run_attempt > 1 && 'debug' || inputs.sentry-log-level }}

      # Copy the app to a temporary folder because the publish step clears the default aab output folder
      - name: Stage AAB
        run: |
          mkdir -p "$AAB_STAGING_DIR"
          cp "${{ steps.setup.outputs.app_module_path }}"/build/outputs/bundle/${{ inputs.flavor }}ReleaseUpload/*.aab "$AAB_STAGING_DIR"

      # Upload the .aab artifact so the upload job (and humans) can download it
      - name: Stash app bundle
        uses: actions/upload-artifact@v7.0.1
        with:
          name: app-bundle
          path: ${{ inputs.working-directory }}${{ env.AAB_STAGING_DIR }}/*.aab
          compression-level: 1
          retention-days: 7
          if-no-files-found: error

  upload:
    name: Upload
    needs: build
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    container:
      image: cimg/android:${{ inputs.android-image-version }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    timeout-minutes: 30
    env:
      AAB_STAGING_DIR: .tmp/publishing_aab
    steps:
      - name: Setup Android environment
        uses: UbiqueInnovation/actions-android/.github/actions/android-app-setup@v2
        with:
          checkout-token: ${{ secrets.ANDROID_JENKINS_PAT }}
          use-git-lfs: ${{ inputs.use-git-lfs }}
          jdk: ${{ inputs.jdk }}
          setup-rust: false
          flavor: ${{ inputs.flavor }}
          app-module: ${{ inputs.app-module }}
          gradle-cache-job-id: '${{ inputs.jdk }}-${{ inputs.app-module }}'

      - name: Unstash app bundle
        uses: actions/download-artifact@v4
        with:
          name: app-bundle
          path: ${{ inputs.working-directory }}${{ env.AAB_STAGING_DIR }}

      - name: Upload to Play Store
        run: |
          ./gradlew :${{ inputs.app-module }}:publish${{ needs.build.outputs.flavor_capitalized }}ReleaseUploadBundle \
            ${{ github.run_attempt > 1 && '--stacktrace --info' || '' }} \
            --artifact-dir "$AAB_STAGING_DIR" \
            -PubiqueMavenUrl=${{ secrets.UB_ARTIFACTORY_URL_ANDROID }} \
            -PubiqueMavenUser=${{ secrets.UB_ARTIFACTORY_USER }} \
            -PubiqueMavenPass=${{ secrets.UB_ARTIFACTORY_PASSWORD }} \
            ${{ secrets.ADDITIONAL_GRADLE_PROPS }}
        env:
          ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}
