name: Run a gradle task

on:
  workflow_call:
    inputs:
      task:
        type: string
        required: true
      gradleArgs:
        type: string
        required: false
      concurrencyGroup:
        type: string
        required: false
        default: ${{ github.workflow }}-${{ github.ref }}
      workingDirectory:
        type: string
        default: './'
        required: false
        description: 'The working directory of the script, for projects where the gradle project is not in the root folder. Must end with a slash.'
      self_hosted_cache_endpoint:
        required: false
        default: 'truenas.local.lan'
        type: string
        description: Should be set for selfhosted builds, but build won't fail without it
      self_hosted_cache_port:
        required: false
        default: 9001
        type: number
      self_hosted_cache_bucket:
        required: false
        default: github-actions-cache
        type: string
      self_hosted_cache_region:
        required: false
        default: local
        type: string
    secrets:
      UB_ARTIFACTORY_URL_ANDROID:
        required: true
      UB_ARTIFACTORY_USERNAME:
        required: true
      UB_ARTIFACTORY_PASSWORD:
        required: true
      self_hosted_cache_access_key:
        required: false
        description: Must be set to use selfhosted cache
      self_hosted_cache_secret_key:
        required: false

jobs:
  task:
    runs-on: ['k8s-runner']
    container:
      image: cimg/android:2024.04.1
    defaults:
      run:
        working-directory: ${{ inputs.workingDirectory }}
    timeout-minutes: 60
    concurrency:
      # Cancel any previous runs that have not yet finished for the configured concurrency group
      group: ${{ inputs.concurrencyGroup }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Install zstd
        run: sudo apt-get install -y zstd
      - name: Cache Gradle packages on self-hosted MinIO
        uses: tespkg/actions-cache@v1.7.1
        with:
          endpoint: ${{ inputs.self_hosted_cache_endpoint }}
          port: ${{ inputs.self_hosted_cache_port }}
          insecure: true
          accessKey: ${{ secrets.self_hosted_cache_access_key }}
          secretKey: ${{ secrets.self_hosted_cache_secret_key }}
          bucket: ${{ inputs.self_hosted_cache_bucket }}
          region: ${{ inputs.self_hosted_cache_region }}
          use-fallback: true
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: cimg-android-${{ inputs.projectKey }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-${{ inputs.task }}
          restore-keys: |
            cimg-android-${{ inputs.projectKey }}-gradle-
      - name: Run Gradle task
        env:
          UB_ARTIFACTORY_URL_ANDROID: ${{ secrets.UB_ARTIFACTORY_URL_ANDROID }}
          UB_ARTIFACTORY_USER: ${{ secrets.UB_ARTIFACTORY_USER }}
          UB_ARTIFACTORY_PASSWORD: ${{ secrets.UB_ARTIFACTORY_PASSWORD }}
        run: ./gradlew ${{ inputs.task }} --build-cache ${{ inputs.gradleArgs }}
