name: Build and Upload to Alpaka

on:
  workflow_call:
    inputs:
      flavor:
        type: string
        required: true
      app-module:
        type: string
        required: false
        default: 'app'
        description: 'The gradle app module (e.g. custom "android:androidApp")'
      concurrency-group:
        type: string
        required: false
        default: ${{ github.workflow }}-${{ github.ref }}
      working-directory:
        type: string
        default: './'
        required: false
        description: 'The working directory of the script, for projects where the gradle project is not in the root folder. Must end with a slash.'
      working-directory-suffix:
        type: string
        default: ''
        required: false
        description: 'Suffix to the working directory of the script, only used for gradle build. Must end with a slash or be empty.'
      cache-key-prefix:
        type: string
        required: false
        default: ${{ github.repository }}
      setup-rust-tool-chain:
        required: false
        default: false
        type: boolean
      runs-on:
        type: string
        required: false
        default: '["k8s-runner"]'
      jdk:
        type: string
        required: false
        default: '21'
        description: The JDK version to use. Default is 21.
      android-image-version:
        type: string
        required: false
        default: '2026.03.1-ndk'
        description: The Android image version to use. Default is 2026.03.1-ndk.
      sentry-log-level:
        type: string
        required: false
        default: 'warn'
        description: 'The Sentry log level to use. Default is "warn". Other options are "trace", "debug", "info" and "error"'
      use-git-lfs:
        required: false
        default: false
        type: boolean
        description: 'Use git lfs during repository checkout'
      pre-build-script:
        required: false
        type: string
        description: 'Bash script that is executed before the actual build'
      git-branch:
        required: false
        type: string
        default: ${{ github.ref_name }}
        description: 'Can be used to override the Git branch name that will be displayed in Alpaka'
      git-sha:
        required: false
        type: string
        default: ${{ github.sha }}
        description: 'Can be used to override the Git commit hash that will be displayed in Alpaka'
    secrets:
      ANDROID_JENKINS_PAT:
        required: true
      UB_ARTIFACTORY_URL_ANDROID:
        required: true
      UB_ARTIFACTORY_USER:
        required: true
      UB_ARTIFACTORY_PASSWORD:
        required: true
      ALPAKA_UPLOAD_KEY:
        required: false
      UBIQUE_POEDITOR_API_KEY:
        required: false
      ADDITIONAL_GRADLE_PROPS:
        required: false
      SENTRY_AUTH_TOKEN:
        required: false
      SSH_KEY:
        description: 'SSH key to import'
        required: false

jobs:
  build:
    name: Build ${{ inputs.flavor }} Flavor
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    container:
      image: cimg/android:${{ inputs.android-image-version }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    timeout-minutes: 60
    concurrency:
      # Cancel any previous runs that have not yet finished for the configured concurrency group
      group: ${{ inputs.concurrency-group }}
      cancel-in-progress: true
    steps:
      # Checkout repository and submodules
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          token: ${{ secrets.ANDROID_JENKINS_PAT }}
          submodules: 'recursive'
          lfs: ${{ inputs.use-git-lfs }}
          fetch-depth: 10

      - name: Ensure ~/.ssh is a directory
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        if: ${{ env.SSH_KEY != '' }}
        shell: bash
        run: |
          if [ -e "$HOME/.ssh" ] && [ ! -d "$HOME/.ssh" ]; then
            echo "~/.ssh exists but is not a directory. Deleting it..."
            rm -f "$HOME/.ssh"
            echo "Removed ~/.ssh."
          else
            echo "~/.ssh is either a directory or does not exist. No action needed."
          fi

      - name: "Add SSH Key"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        if: ${{ env.SSH_KEY != '' }}
        uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: "Add GitHub SSH keys to the known_hosts file"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        if: ${{ env.SSH_KEY != '' }}
        run: |
          cat >> ~/.ssh/known_hosts <<EOF
          github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
          github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
          EOF
        shell: bash

      # Run prebuild script
      - name: "Pre Build Script"
        if: ${{ inputs.pre-build-script }}
        run: ${{ inputs.pre-build-script }}

      # Set build variables for reuse in multiple steps
      - name: Set Build Variables
        id: vars
        shell: bash
        run: |
          flavor=${{ inputs.flavor }}
          echo "flavor_capitalized=${flavor~}" >> "$GITHUB_OUTPUT"
          
          buildBatch=${{ github.run_id }}
          echo "build_batch=$buildBatch" >> "$GITHUB_OUTPUT"
          
          buildId=$(cat /proc/sys/kernel/random/uuid)
          echo "build_id=$buildId" >> "$GITHUB_OUTPUT"
          
          buildNumber=${{ github.run_number }}
          echo "build_number=$buildNumber" >> "$GITHUB_OUTPUT"

      - name: write build_id to file
        run: echo "${{ steps.vars.outputs.build_id }}" > build_id.txt

      - name: upload build_id as artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ inputs.flavor }}_build_id
          compression-level: 0
          path: ${{ inputs.working-directory }}/build_id.txt

      # Setup JDK environment
      - name: Set up JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'zulu'
          java-version: ${{ inputs.jdk }}

      - name: Install zstd
        run: sudo apt-get install -y zstd

      # Setup rust Tool Chain
      - name: Setup rust Tool Chain
        uses: actions-rust-lang/setup-rust-toolchain@v1.15.4
        if: ${{ inputs.setup-rust-tool-chain }}

      # Build and upload app to Alpaka
      - name: Build app
        run: |
          if [ -n "${{ inputs.working-directory-suffix }}" ]; then
            cd "${{ inputs.working-directory-suffix }}"
          fi
          ./gradlew :${{ inputs.app-module }}:clean :${{ inputs.app-module }}:assembleAndPublishToAlpaka${{ steps.vars.outputs.flavor_capitalized }}Release \
            ${{ github.run_attempt > 1 && '--stacktrace --info' || '' }} \
            -PubiqueMavenUrl=${{ secrets.UB_ARTIFACTORY_URL_ANDROID }} \
            -PubiqueMavenUser=${{ secrets.UB_ARTIFACTORY_USER }} \
            -PubiqueMavenPass=${{ secrets.UB_ARTIFACTORY_PASSWORD }} \
            -PubiquePoEditorAPIKey=${{ secrets.UBIQUE_POEDITOR_API_KEY }} \
            -Pbuild_batch=${{ steps.vars.outputs.build_batch }} \
            -Pbuild_id=${{ steps.vars.outputs.build_id }} \
            -Pbuild_number=${{ steps.vars.outputs.build_number }} \
            -Pbranch=${{ inputs.git-branch }} \
            -PcommitHash=${{ inputs.git-sha }} \
            ${{ secrets.ADDITIONAL_GRADLE_PROPS }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_LOG_LEVEL: ${{ github.run_attempt > 1 && 'debug' || inputs.sentry-log-level }}
          ALPAKA_UPLOAD_KEY: ${{ secrets.ALPAKA_UPLOAD_KEY }}

      # Write Alpaka build info to GitHub job summary
      - name: Alpaka Build Summary
        run: |
          echo '### Alpaka Build Info' >> $GITHUB_STEP_SUMMARY
          echo '| | |' >> $GITHUB_STEP_SUMMARY
          echo '|---|---|' >> $GITHUB_STEP_SUMMARY
          echo '| Build Batch | ${{ steps.vars.outputs.build_batch }} |' >> $GITHUB_STEP_SUMMARY
          echo '| Build ID | ${{ steps.vars.outputs.build_id }} |' >> $GITHUB_STEP_SUMMARY
          echo '| Build Number | ${{ steps.vars.outputs.build_number }} |' >> $GITHUB_STEP_SUMMARY
