name: Generate Test Cases for PR

on:
  workflow_call:
    inputs:
      PR_NUMBER:
        type: string
        required: true
      GITHUB_REPOSITORY:
        type: string
        required: true
    secrets:
      OPENAI_API_KEY:
        required: true
      GH_TOKEN:
        required: true

jobs:
  generate-test-cases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR repo
        uses: actions/checkout@v4

      - name: Checkout this workflow repo (with script)
        uses: actions/checkout@v4
        with:
          repository:  UbiqueInnovation/actions-android
          ref: feature/generate-test-cases
          path: test-action 
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai requests
        
      - name: Generate and Comment Test Cases
        run: python test-action/generate-testcases.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ inputs.PR_NUMBER }}
          GITHUB_REPOSITORY: ${{ inputs.GITHUB_REPOSITORY }}
