name: Generate Test Cases for PR

on:
  workflow_call:
    inputs:
      flavor:
        type: string
        required: true
      concurrencyGroup:
        type: string
        required: false
        default: ${{ github.workflow }}-${{ github.ref }}
    secrets:
      OPENAI_API_KEY:
        required: true
      GH_TOKEN:
        required: true
      PR_NUMBER:
        required: true
      GITHUB_REPOSITORY:
        required: true

jobs:
  generate-test-cases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai requests

      - name: Generate and Comment Test Cases
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python generate-testcases/generate-testcases.py
