name: Build and publish library artifact

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        default: './'
        required: false
        description: 'The working directory of the script, for projects where the gradle project is not in the root folder. Must end with a slash.'
      lib-module:
        type: string
        required: false
        default: 'lib'
        description: 'The name of the gradle module of the library (similar to the app module)'
      version-name-suffix:
        type: string
        default: ''
        required: false
        description: 'A suffix to be appended to the version name. Empty by default for release builds'
      gradle-properties-path:
        type: string
        default: './gradle.properties'
        required: false
        description: 'The path to the gradle.properties file that contains the POM_ARTIFACT_VERSION'
      jdk:
        type: string
        required: false
        default: '21'
        description: The JDK version to use. Default is 21.
      use-git-lfs:
        required: false
        default: false
        type: boolean
        description: 'Use git lfs during repository checkout'
    secrets:
      ANDROID_JENKINS_PAT:
        required: true
      UB_ARTIFACTORY_URL_ANDROID:
        required: true
      UB_ARTIFACTORY_USER:
        required: true
      UB_ARTIFACTORY_PASSWORD:
        required: true


jobs:
  build:
    name: Build library
    runs-on: ["self-hosted", "macOS"]
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    timeout-minutes: 60
    concurrency:
      # Cancel any previous runs that have not yet finished for the configured concurrency group
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      # Checkout repository and submodules
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          token: ${{ secrets.ANDROID_JENKINS_PAT }}
          submodules: 'recursive'
          lfs: ${{ inputs.use-git-lfs }}

      # Setup JDK environment
      - name: Set up JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'zulu'
          java-version: ${{ inputs.jdk }}

      # Append version name suffix
      - name: Append version name suffix
        id: version
        if: ${{ inputs.version-name-suffix }} != ''
        run: |
          if grep -q "VERSION_NAME=" ${{ inputs.gradle-properties-path }}; then
            sed -i '' "/^VERSION_NAME=/s/$/${{ inputs.version-name-suffix }}/" ${{ inputs.gradle-properties-path }}
          else
            echo "Could not find VERSION_NAME gradle property in ${{ inputs.gradle-properties-path }}"
            exit 1
          fi

      # Run the Gradle publish task
      - name: Build and publish artifact
        run: |
          ./gradlew :${{ inputs.lib-module }}:publish \
            ${{ github.run_attempt > 1 && '--stacktrace --debug' || '' }} \
            -PubiqueMavenUrl=${{ secrets.UB_ARTIFACTORY_URL_ANDROID }} \
            -PubiqueMavenUser=${{ secrets.UB_ARTIFACTORY_USER }} \
            -PubiqueMavenPass=${{ secrets.UB_ARTIFACTORY_PASSWORD }}
        env:
          UB_ARTIFACTORY_URL_ANDROID: ${{ secrets.UB_ARTIFACTORY_URL_ANDROID }}
          UB_ARTIFACTORY_USER: ${{ secrets.UB_ARTIFACTORY_USER }}
          UB_ARTIFACTORY_PASSWORD: ${{ secrets.UB_ARTIFACTORY_PASSWORD }}
